// <auto-generated />
namespace _200395812A1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Publisher : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Publisher));
        
        string IMigrationMetadata.Id
        {
            get { return "201906120513346_Publisher"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
